#!/usr/bin/env python3

# This file is part of the libopencm3 project.
# 
# Copyright (C) 2012 chrysn <chrysn@fsfe.org>
# Copyright (C) 2023 Karl Schultheisz <k@kdsch.org>
# 
# This library is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
# 
# You should have received a copy of the GNU Lesser General Public License
# along with this library. If not, see <http://www.gnu.org/licenses/>.

"""Generate an nvic.h header from a small JSON file describing the interrupt
numbers.

Code generation is chosen here because the resulting C code needs to be very
repetetive (definition of the IRQ numbers, function prototypes, weak fallback
definition and vector table definition), all being very repetitive. No portable
method to achieve the same thing with C preprocessor is known to the author.
(Neither is any non-portable method, for that matter.)"""

import sys
import os
import os.path
import json

template_nvic_h = '''\
/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script from {sourcefile}
 */

#ifndef {includeguard}
#define {includeguard}

#include <libopencm3/cm3/nvic.h>

/** @defgroup CM3_nvic_defines_irqs User interrupts for {partname_humanreadable}
    @ingroup CM3_nvic_defines

    @{{*/

{irqdefinitions}

#define NVIC_IRQ_COUNT {irqcount}

/**@}}*/

/** @defgroup CM3_nvic_isrprototypes_{partname_doxygen} User interrupt service routines (ISR) prototypes for {partname_humanreadable}
    @ingroup CM3_nvic_isrprototypes

    @{{*/

BEGIN_DECLS

{isrprototypes}

END_DECLS

/**@}}*/

#endif /* {includeguard} */
'''

template_vector_nvic_h = '''\
/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script.
 *
 * This part needs to get included in the compilation unit where
 * blocking_handler gets defined due to the way #pragma works.
 */


/** @defgroup CM3_nvic_isrdecls_{partname_doxygen} User interrupt service routines (ISR) defaults for {partname_humanreadable}
    @ingroup CM3_nvic_isrdecls

    @{{*/

{isrdecls}

/**@}}*/

/* Initialization template for the interrupt vector table. This definition is
 * used by the startup code generator (vector.c) to set the initial values for
 * the interrupt handling routines to the chip family specific _isr weak
 * symbols. */

#define IRQ_HANDLERS \\
    {vectortableinitialization}
'''

template_cmsis_h = '''\
/* This file is part of the libopencm3 project.
 *
 * It was generated by the irq2nvic_h script.
 *
 * These definitions bend every interrupt handler that is defined CMSIS style
 * to the weak symbol exported by libopencm3.
 */

{cmsisbends}
'''

def convert(kind_flag, infile, outfile):
    data = json.load(infile)
    irq2name = list(enumerate(data['irqs']) if isinstance(data['irqs'], list) else data['irqs'].items())
    irqnames = [v for (k,v) in irq2name]

    if isinstance(data['irqs'], list):
        data['irqcount'] = len(irq2name)
    else:
        data['irqcount'] = max([int(x) for x in data['irqs'].keys()]) + 1

    data['irqdefinitions'] = "\n".join('#define NVIC_%s_IRQ %d'%(v.upper(),int(k)) for (k,v) in irq2name)
    data['isrprototypes'] = "\n".join('void %s_isr(void);'%name.lower() for name in irqnames)
    data['isrdecls'] = "\n".join('void %s_isr(void) __attribute__((weak, alias("blocking_handler")));'%name.lower() for name in irqnames)
    data['vectortableinitialization'] = ', \\\n    '.join('[NVIC_%s_IRQ] = %s_isr'%(name.upper(), name.lower()) for name in irqnames)
    data['cmsisbends'] = "\n".join("#define %s_IRQHandler %s_isr"%(name.upper(), name.lower()) for name in irqnames)
    data['sourcefile'] = infile.name

    templates = {
        '--nvic': template_nvic_h,
        '--vector_nvic': template_vector_nvic_h,
        '--irqhandlers': template_cmsis_h,
    }

    assert kind_flag in templates.keys()
    outfile.write(templates[kind_flag].format(**data))

def makeparentdir(filename):
    try:
        os.makedirs(os.path.dirname(filename))
    except OSError:
        # where is my 'mkdir -p'?
        pass

def main():
    kind_flag = sys.argv[1]
    infile = sys.argv[2]
    outfile = sys.argv[3]
    convert(kind_flag, open(infile), open(outfile, 'w'))

if __name__ == "__main__":
    main()
